export const stateOptions = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AS', label: 'American Samoa' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'DC', label: 'District Of Columbia' },
  { value: 'FM', label: 'Federated States Of Micronesia' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'GU', label: 'Guam' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MH', label: 'Marshall Islands' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'MP', label: 'Northern Mariana Islands' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PW', label: 'Palau' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'PR', label: 'Puerto Rico' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VI', label: 'Virgin Islands' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
];

export const state = [
  { id: 1, label: 'LA', value: 'LA' },
  { id: 2, label: 'TX', value: 'TX' },
  { id: 3, label: 'OK', value: 'OK' },
  { id: 4, label: 'CO', value: 'CO' },
  { id: 5, label: 'AR', value: 'AR' },
  { id: 6, label: 'FT', value: 'FT' },
  { id: 7, label: 'MO', value: 'MO' },
  { id: 8, label: 'NM', value: 'NM' },
  { id: 9, label: 'PA', value: 'PA' },
  { id: 10, label: 'NJ', value: 'NJ' },
  { id: 11, label: 'IL', value: 'IL' },
  { id: 12, label: 'MA', value: 'MA' },
  { id: 13, label: 'NH', value: 'NH' },
  { id: 14, label: 'MD', value: 'MD' },
  { id: 15, label: 'VA', value: 'VA' },
  { id: 16, label: 'MN', value: 'MN' },
  { id: 17, label: 'NY', value: 'NY' },
  { id: 18, label: 'IN', value: 'IN' },
  { id: 19, label: 'SD', value: 'SD' },
  { id: 20, label: 'DE', value: 'DE' },
  { id: 21, label: 'WV', value: 'WV' },
  { id: 22, label: 'RI', value: 'RI' },
  { id: 23, label: 'ME', value: 'ME' },
  { id: 24, label: 'NE', value: 'NE' },
  { id: 25, label: 'WI', value: 'WI' },
  { id: 26, label: 'OH', value: 'OH' },
  { id: 27, label: 'MI', value: 'MI' },
  { id: 28, label: 'CT', value: 'CT' },
  { id: 29, label: 'ND', value: 'ND' },
  { id: 30, label: 'IA', value: 'IA' },
  { id: 31, label: 'VN', value: 'VN' },
  { id: 32, label: 'VT', value: 'VT' },
  { id: 33, label: 'MT', value: 'MT' },
  { id: 34, label: 'NC', value: 'NC' },
  { id: 35, label: 'FL', value: 'FL' },
  { id: 36, label: 'KY', value: 'KY' },
  { id: 37, label: 'GA', value: 'GA' },
  { id: 38, label: 'AL', value: 'AL' },
  { id: 39, label: 'SC', value: 'SC' },
  { id: 40, label: 'TN', value: 'TN' },
  { id: 41, label: 'KS', value: 'KS' },
  { id: 42, label: 'MS', value: 'MS' },
  { id: 43, label: 'OR', value: 'OR' },
  { id: 44, label: 'CA', value: 'CA' },
  { id: 45, label: 'AZ', value: 'AZ' },
  { id: 46, label: 'WA', value: 'WA' },
  { id: 47, label: 'UT', value: 'UT' },
  { id: 48, label: 'NV', value: 'NV' },
  { id: 49, label: 'HI', value: 'HI' },
  { id: 50, label: 'ID', value: 'ID' },
];
